# Generated by Django 6.0.7 on 2026-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
