# Generated by Django 6.0.7 on 2026-07-25 14:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_estate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='estate',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
