# Generated by Django 6.0.7 on 2026-07-25 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_estate_status_alter_estate_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='gate_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='estate_images/'),
        ),
    ]
